root@rohan-virtual-machine:/etc/ansible/Ansible_Playbooks# cat 3paloalto_ansible_playbook.yml
---
- hosts: PANOS
  gather_facts: false
  connection: local

  collections:
  - paloaltonetworks.panos

  vars:
   provider_paloalto:
      ip_address: "{{ ansible_host }}"
      username: "admin"
      password: "Cisco@123"

  tasks:
  - name: Create tag object 'Prod'
    paloaltonetworks.panos.panos_tag_object:
      provider: '{{ provider_paloalto }}'
      name: 'TEST_TAG_PROD'
      color: 'forest green'
      comments: 'Test Tag for Prod Environment'

  - name: Create object 'Test-prod-obj'
    paloaltonetworks.panos.panos_address_object:
      provider: '{{ provider_paloalto }}'
      name: 'Prod-obj-test'
      value: '1.1.1.1'
      description: 'object to test prod'
      tag: ['TEST_TAG_PROD']

  - name: Create object 'Test-prod-obj'
    paloaltonetworks.panos.panos_address_object:
      provider: '{{ provider_paloalto }}'
      name: 'Prod-obj-test-1'
      value: '2.2.2.2'
      description: 'object to test prod'
      tag: ['TEST_TAG_PROD']

  - name: Create object 'Test-prod-obj'
    paloaltonetworks.panos.panos_address_object:
      provider: '{{ provider_paloalto }}'
      name: 'Prod-obj-test-2'
      value: '3.3.3.3'
      description: 'object to test prod'
      tag: ['TEST_TAG_PROD']

  - name: Create object group 'Obj-Group-Prod'
    paloaltonetworks.panos.panos_address_group:
      provider: '{{ provider_paloalto }}'
      name: 'Test-Obj-Group-Prod'
      static_value: ['Prod-obj-test', 'Prod-obj-test-1', 'Prod-obj-test-2']
      tag: ['TEST_TAG_PROD']

  - name: Create service group 'Prod-Services'
    paloaltonetworks.panos.panos_service_group:
      provider: '{{ provider_paloalto }}'
      name: 'Test-Prod-Services-Group'
      value: ['ssh-tcp-22', 'service-https']

  - name: add SSH inbound rule to Panorama device group
    paloaltonetworks.panos.panos_security_rule:
      provider: '{{ provider_paloalto }}'
      rule_name: 'Extnernal to DMZ Rule'
      description: 'To allow SSH and HTTPS from External to DMZ'
      tag_name: ['TEST_TAG_PROD']
      source_zone: ['External']
      source_ip: ['any']
      destination_zone: ['DMZ']
      destination_ip: ['Test-Obj-Group-Prod']
      application: ['ssh', 'intervals']
      service: ['Test-Prod-Services-Group']
      action: 'allow'

  - name: add a nat rule
    paloaltonetworks.panos.panos_nat_rule2:
      provider: '{{ provider_paloalto }}'
      name: 'NAT rule for DMZ server'
      description: 'NAT rule to allow traffic from Internet'
      nat_type: 'ipv4'
      from_zones: ['any']
      to_zones: ['DMZ']
      to_interface: 'ethernet1/1'
      service: 'any'
      source_addresses: ['any']
      destination_addresses: ['172.16.48.48']
      source_translation_type: 'dynamic-ip-and-port'
      source_translation_address_type: 'interface-address'
      source_translation_interface: 'ethernet1/1'
...
root@rohan-virtual-machine:/etc/ansible/Ansible_Playbooks#

###############################################################################################
#############################################Result############################################
###############################################################################################

root@rohan-virtual-machine:/etc/ansible/Ansible_Playbooks# ansible-playbook 3paloalto_ansible_playbook.yml

PLAY [PANOS] **********************************************************************************************************************************************************************************************

TASK [Create tag object 'Prod'] ***************************************************************************************************************************************************************************
changed: [PA1]

TASK [Create object 'Test-prod-obj'] **********************************************************************************************************************************************************************
changed: [PA1]

TASK [Create object 'Test-prod-obj'] **********************************************************************************************************************************************************************
changed: [PA1]

TASK [Create object 'Test-prod-obj'] **********************************************************************************************************************************************************************
changed: [PA1]

TASK [Create object group 'Obj-Group-Prod'] ***************************************************************************************************************************************************************
changed: [PA1]

TASK [Create service group 'Prod-Services'] ***************************************************************************************************************************************************************
changed: [PA1]

TASK [add SSH inbound rule to Panorama device group] ******************************************************************************************************************************************************
changed: [PA1]

TASK [add a nat rule] *************************************************************************************************************************************************************************************
changed: [PA1]

PLAY RECAP ************************************************************************************************************************************************************************************************
PA1                        : ok=8    changed=8    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

root@rohan-virtual-machine:/etc/ansible/Ansible_Playbooks#
