---

inventory:
  plugin: SimpleInventory
  options:
    host_file: "hosts.yml"
    group_file: "groups.yml"
    defaults_file: "default.yml"

runners:
  plugin: threaded
  options:
    num_workers: 10

...